// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBAmok16Vky8w_xqSXPPw5jzSssAF4lRN0',
    appId: '1:621784557779:web:6691600b99415cfd890c26',
    messagingSenderId: '621784557779',
    projectId: 'learn-flutter-68-2-14a5e',
    authDomain: 'learn-flutter-68-2-14a5e.firebaseapp.com',
    storageBucket: 'learn-flutter-68-2-14a5e.firebasestorage.app',
    measurementId: 'G-KF3B9619LL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDzWAmKM4mWr6S01FO4IGUxVowDkfstKHQ',
    appId: '1:621784557779:android:3e73ebb76897c443890c26',
    messagingSenderId: '621784557779',
    projectId: 'learn-flutter-68-2-14a5e',
    storageBucket: 'learn-flutter-68-2-14a5e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAsMph_wCll8uUbAW48PIBYWNKXq8sviLs',
    appId: '1:621784557779:ios:a87032098ea547d3890c26',
    messagingSenderId: '621784557779',
    projectId: 'learn-flutter-68-2-14a5e',
    storageBucket: 'learn-flutter-68-2-14a5e.firebasestorage.app',
    iosBundleId: 'com.example.learnFlutter6822',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAsMph_wCll8uUbAW48PIBYWNKXq8sviLs',
    appId: '1:621784557779:ios:a87032098ea547d3890c26',
    messagingSenderId: '621784557779',
    projectId: 'learn-flutter-68-2-14a5e',
    storageBucket: 'learn-flutter-68-2-14a5e.firebasestorage.app',
    iosBundleId: 'com.example.learnFlutter6822',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBAmok16Vky8w_xqSXPPw5jzSssAF4lRN0',
    appId: '1:621784557779:web:8c1359713709c0bc890c26',
    messagingSenderId: '621784557779',
    projectId: 'learn-flutter-68-2-14a5e',
    authDomain: 'learn-flutter-68-2-14a5e.firebaseapp.com',
    storageBucket: 'learn-flutter-68-2-14a5e.firebasestorage.app',
    measurementId: 'G-ETSY3PXY0Q',
  );
}
